# Generated by Django 3.0.5 on 2020-11-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otpapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='material_type',
            new_name='paper_material',
        ),
    ]
