# Generated by Django 3.0.5 on 2020-11-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpapp', '0002_auto_20201111_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=25),
        ),
        migrations.AddField(
            model_name='jobs',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PARTIAL_PAYMENT', 'PARTIAL_PAYMENT'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=25),
        ),
        migrations.AddField(
            model_name='jobs',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
