# Generated by Django 3.0.5 on 2020-10-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otpapp', '0002_auto_20201027_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fisrtname',
            new_name='firstname',
        ),
    ]
