# Generated by Django 3.1.2 on 2020-11-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpapp', '0004_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='user_documents'),
        ),
    ]
